
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyeymnkpvgmmryorttfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZXltbmtwdmdtbXJ5b3J0dGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzUxNTQsImV4cCI6MjA1NzcxMTE1NH0.ihWvomMu1EJHv6R5ob7nsO1817Sz3oL6oSV0A_M4uR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
